#!/usr/bin/env bash
# Idlegit demo workspace — fully sandboxed, no global git/system state.
#
# `up`     — create bare repos + start `git daemon` + register three
#            idlegit workspaces (commit-demo, sync-demo, idlegit). Default
#            active workspace is `commit-demo`.
# `down`   — kill the daemon, remove the demo dirs.
# `status` — show whether the daemon is alive and where things live.
#
# Nothing here writes to your real ~/.gitconfig, ~/.ssh, or
# ~/.config/idlegit — every git/idlegit lookup is redirected via $HOME,
# $GIT_CONFIG_GLOBAL, and $IDLEGIT_CONFIG_DIR to /tmp dirs that `down`
# removes wholesale.
#
# Workspace 3 (`idlegit`) clones the real github.com:jtelwar/Idlegit so
# we can demonstrate launching a real GitHub Action. It needs `gh` auth,
# which we COPY (not symlink) from ~/.config/gh into the sandbox so
# nothing the demo does can write back into your real gh config.

set -euo pipefail

# ---- config ----------------------------------------------------------------
DEMO_ROOT="${DEMO_ROOT:-/tmp/idlegit-demo}"
DEMO_HOME="$DEMO_ROOT/home"
DEMO_REMOTES="$DEMO_ROOT/remotes"
DEMO_WORKSPACES_ROOT="$DEMO_ROOT/workspaces"
DEMO_TMP="$DEMO_ROOT/tmp"
PID_FILE="$DEMO_ROOT/daemon.pid"
PORT="${PORT:-9418}"

# Workspace 1: "commit-demo" — shared toolkit lib + three apps. One app
# has a dirty submodule checkout (demo opens with cursor on it).
W1_DIR="$DEMO_WORKSPACES_ROOT/commit-demo"
W1_LIB=nimbus-toolkit
W1_APPS=(nimbus-cms nimbus-shop nimbus-portal)

# Workspace 2: "sync-demo" — nested submodules with three different pins
# of the same canonical, set up to make smart-sync visually obvious.
W2_DIR="$DEMO_WORKSPACES_ROOT/sync-demo"
W2_SUPERS=(atlas-server atlas-web atlas-mobile)
W2_LIBS=(atlas-core atlas-ui)
W2_STANDALONES=(atlas-docs)

# Workspace 3: "idlegit" — real clone of jtelwar/Idlegit for action demo.
W3_DIR="$DEMO_WORKSPACES_ROOT/idlegit"
IDLEGIT_REMOTE="${IDLEGIT_REMOTE:-https://github.com/jtelwar/Idlegit.git}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# ---- helpers ---------------------------------------------------------------
say()  { printf '\033[1;36m▸\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

sandbox_env() {
  export HOME="$DEMO_HOME"
  export GIT_CONFIG_GLOBAL="$DEMO_HOME/.gitconfig"
  export GIT_CONFIG_SYSTEM=/dev/null
  export IDLEGIT_CONFIG_DIR="$DEMO_HOME/.config/idlegit"
  # git 2.38+ blocks the `git://` protocol for submodules by default
  # (CVE-2022-39253). Allow it inside the sandbox only.
  export GIT_ALLOW_PROTOCOL="git:http:https:ssh:file"
}

write_sandbox_gitconfig() {
  mkdir -p "$DEMO_HOME"
  cat >"$DEMO_HOME/.gitconfig" <<'EOF'
[user]
    name = Idlegit Demo
    email = demo@idlegit.local
[init]
    defaultBranch = main
[protocol "git"]
    allow = always
[protocol "file"]
    allow = always
[advice]
    detachedHead = false
[submodule]
    recurse = false
EOF
}

# Copy the user's gh CLI auth into the sandbox so workspace 3 can trigger
# workflows. We copy (not symlink) so the demo can't accidentally write
# back into the real config. Tolerates missing config (workspace 3 still
# clones; action triggers just won't work).
copy_gh_auth() {
  local src="${XDG_CONFIG_HOME:-$REAL_HOME/.config}/gh"
  local dst="$DEMO_HOME/.config/gh"
  if [ -d "$src" ]; then
    mkdir -p "$DEMO_HOME/.config"
    cp -R "$src" "$dst"
    ok "copied gh auth into sandbox"
  else
    warn "no ~/.config/gh found — workspace 3 action trigger will fail"
  fi
}

# Three workspaces, with sensible overrides so the auto-propagation in
# workspace 1's demo actually happens without further key presses.
write_idlegit_workspaces() {
  local cfg_dir="$DEMO_HOME/.config/idlegit"
  mkdir -p "$cfg_dir"
  cat >"$cfg_dir/idlegit.workspaces" <<EOF
# Auto-generated by scripts/demo/demo-workspace.sh — do not edit by hand.
[idlegit]
active_workspace = commit-demo

[workspace.commit-demo]
folders =
    $W1_DIR
default_auto_stage = true
default_auto_push = true
default_auto_ff = true
default_auto_push_submodule_parent = true
default_align_heads = true

[workspace.sync-demo]
folders =
    $W2_DIR
default_auto_stage = true
default_auto_push = true
default_auto_ff = true
default_align_heads = true

[workspace.idlegit]
folders =
    $W3_DIR
default_auto_stage = false
default_auto_push = false
track_actions_default = true
EOF
}

# Create bare repo + seed commits. Records each commit SHA into
# $DEMO_TMP/<name>.shas so submodule wiring can pin specific commits.
seed_bare() {
  local name="$1"; shift
  local commits=("$@")
  local bare="$DEMO_REMOTES/$name.git"
  local work="$DEMO_TMP/seed-$name"

  git init --bare -q -b main "$bare"
  rm -rf "$work"
  git init -q -b main "$work"
  (
    cd "$work"
    : >"$DEMO_TMP/$name.shas"
    local i=0
    for msg in "${commits[@]}"; do
      i=$((i + 1))
      printf '# %s\n\n## %s\n' "$name" "$msg" >README.md
      printf 'step %d: %s\n' "$i" "$msg" >>HISTORY.md
      git add -A
      git -c user.name="Idlegit Demo" -c user.email="demo@idlegit.local" \
          commit -q -m "$msg"
      git rev-parse HEAD >>"$DEMO_TMP/$name.shas"
    done
    git remote add origin "$bare"
    git push -q origin main
  )
  rm -rf "$work"
}

# Add `child` as a submodule of `parent` at `pin_sha`, then commit+push.
add_submodule_pinned() {
  local parent="$1" child="$2" pin_sha="$3" path="$4"
  local work="$DEMO_TMP/seed-$parent"

  (
    cd "$work"
    git -c protocol.git.allow=always \
        submodule add -q "git://localhost:$PORT/$child.git" "$path"
    (
      cd "$path"
      git checkout -q "$pin_sha"
    )
    git -c user.name="Idlegit Demo" -c user.email="demo@idlegit.local" \
        commit -q -am "add $child submodule pinned at ${pin_sha:0:7}"
    git push -q origin main
  )
}

# Pin a submodule at HEAD of its remote (simpler variant used when all
# parents agree on the commit).
add_submodule_head() {
  local parent="$1" child="$2" path="$3"
  local work="$DEMO_TMP/seed-$parent"

  (
    cd "$work"
    git -c protocol.git.allow=always \
        submodule add -q "git://localhost:$PORT/$child.git" "$path"
    git -c user.name="Idlegit Demo" -c user.email="demo@idlegit.local" \
        commit -q -am "add $child submodule"
    git push -q origin main
  )
}

# ---- workspace builders ----------------------------------------------------
build_workspace_commit_demo() {
  say "[ws1] seeding toolkit + apps for commit-demo"
  seed_bare "$W1_LIB" \
    "init toolkit" \
    "add http helpers" \
    "add cache utility"
  for app in "${W1_APPS[@]}"; do
    seed_bare "$app" \
      "init $app" \
      "wire app entrypoint"
  done

  # Each app contains the toolkit as a submodule at libs/toolkit, all
  # pinned at the toolkit's current HEAD.
  for app in "${W1_APPS[@]}"; do
    rm -rf "$DEMO_TMP/seed-$app"
    git clone -q "git://localhost:$PORT/$app.git" "$DEMO_TMP/seed-$app"
    (cd "$DEMO_TMP/seed-$app" && git remote set-url origin "$DEMO_REMOTES/$app.git")
    add_submodule_head "$app" "$W1_LIB" "libs/toolkit"
    rm -rf "$DEMO_TMP/seed-$app"
  done

  say "[ws1] cloning checkouts into $W1_DIR"
  mkdir -p "$W1_DIR"
  (
    cd "$W1_DIR"
    for app in "${W1_APPS[@]}"; do
      git clone -q --recurse-submodules "git://localhost:$PORT/$app.git"
    done
  )

  # Demo arc:
  #   1. nimbus-cms/libs/toolkit has a dirty edit (the submodule checkout
  #      the user will suggest+commit+push first).
  #   2. nimbus-cms, nimbus-shop, nimbus-portal each have an unrelated
  #      dirty edit in their own working tree — these get cleaned up by
  #      "suggest all + commit all" after returning from workspace 2.
  printf '\ndef new_helper():\n    return "v2"\n' \
    >>"$W1_DIR/${W1_APPS[0]}/libs/toolkit/HISTORY.md"

  for app in "${W1_APPS[@]}"; do
    printf '\n## TODO\n- polish %s before launch\n' "$app" \
      >>"$W1_DIR/$app/README.md"
  done
}

build_workspace_sync_demo() {
  say "[ws2] seeding nested-submodule workspace for sync-demo"
  seed_bare "${W2_LIBS[0]}" \
    "init core" "add config loader" "add cache layer" \
    "fix race in cache" "introduce metrics hook"
  seed_bare "${W2_LIBS[1]}" \
    "init ui kit" "add button + input" "add modal primitive"
  seed_bare "${W2_STANDALONES[0]}" \
    "init docs" "describe architecture"
  for sp in "${W2_SUPERS[@]}"; do
    seed_bare "$sp" "init $sp" "wire up entrypoint"
  done

  CORE_SHAS=()
  while IFS= read -r line; do CORE_SHAS+=("$line"); done <"$DEMO_TMP/${W2_LIBS[0]}.shas"
  local core_old="${CORE_SHAS[1]}"
  local core_mid="${CORE_SHAS[2]}"
  local core_new="${CORE_SHAS[4]}"

  for sp in "${W2_SUPERS[@]}"; do
    rm -rf "$DEMO_TMP/seed-$sp"
    git clone -q "git://localhost:$PORT/$sp.git" "$DEMO_TMP/seed-$sp"
    (cd "$DEMO_TMP/seed-$sp" && git remote set-url origin "$DEMO_REMOTES/$sp.git")
  done

  add_submodule_pinned "${W2_SUPERS[0]}" "${W2_LIBS[0]}" "$core_old" "libs/core"
  add_submodule_pinned "${W2_SUPERS[1]}" "${W2_LIBS[0]}" "$core_mid" "libs/core"
  add_submodule_pinned "${W2_SUPERS[2]}" "${W2_LIBS[0]}" "$core_new" "libs/core"

  local ui_head
  ui_head="$(tail -n1 "$DEMO_TMP/${W2_LIBS[1]}.shas")"
  add_submodule_pinned "${W2_SUPERS[1]}" "${W2_LIBS[1]}" "$ui_head" "libs/ui"
  add_submodule_pinned "${W2_SUPERS[2]}" "${W2_LIBS[1]}" "$ui_head" "libs/ui"

  for sp in "${W2_SUPERS[@]}"; do rm -rf "$DEMO_TMP/seed-$sp"; done

  say "[ws2] cloning checkouts into $W2_DIR"
  mkdir -p "$W2_DIR"
  (
    cd "$W2_DIR"
    for sp in "${W2_SUPERS[@]}"; do
      git clone -q --recurse-submodules "git://localhost:$PORT/$sp.git"
    done
    for s in "${W2_STANDALONES[@]}"; do
      git clone -q "git://localhost:$PORT/$s.git"
    done
  )

  # Detached HEAD on one submodule checkout, ahead-by-one on one super.
  (
    cd "$W2_DIR/${W2_SUPERS[1]}/libs/core"
    git checkout -q --detach HEAD
  )
  (
    cd "$W2_DIR/${W2_SUPERS[2]}"
    printf 'TODO: ship 2.0\n' >ROADMAP.md
    git add ROADMAP.md
    git -c user.name="Idlegit Demo" -c user.email="demo@idlegit.local" \
        commit -q -m "wip: roadmap"
  )
}

build_workspace_idlegit() {
  say "[ws3] cloning $IDLEGIT_REMOTE into $W3_DIR"
  mkdir -p "$W3_DIR"
  if ! git -C "$W3_DIR" clone -q "$IDLEGIT_REMOTE" idlegit 2>&1; then
    warn "could not clone idlegit (auth / network). Workspace 3 will be empty."
  fi
}

# ---- daemon lifecycle ------------------------------------------------------
start_daemon() {
  mkdir -p "$DEMO_REMOTES"
  git daemon \
    --base-path="$DEMO_REMOTES" \
    --export-all \
    --reuseaddr \
    --listen=127.0.0.1 \
    --port="$PORT" \
    --detach \
    --pid-file="$PID_FILE"

  local tries=0
  until nc -z 127.0.0.1 "$PORT" 2>/dev/null; do
    tries=$((tries + 1))
    [ "$tries" -gt 50 ] && die "git daemon did not bind to :$PORT"
    sleep 0.05
  done
}

stop_daemon() {
  if [ -f "$PID_FILE" ]; then
    local pid
    pid="$(cat "$PID_FILE")"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      ok "stopped git daemon (pid $pid)"
    fi
    rm -f "$PID_FILE"
  fi
}

# ---- subcommands -----------------------------------------------------------
cmd_up() {
  command -v git >/dev/null || die "git not on PATH"
  command -v nc  >/dev/null || die "nc not on PATH (used to poll daemon)"

  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    die "demo daemon already running (pid $(cat "$PID_FILE")) — run \`$0 down\` first"
  fi

  if lsof -i ":$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    die "port $PORT already in use — set PORT=<other> and retry"
  fi

  # Capture the real HOME before we clobber it for the sandbox — needed
  # to find the user's gh auth dir.
  REAL_HOME="$HOME"

  say "wiping any previous demo state at $DEMO_ROOT"
  rm -rf "$DEMO_ROOT"
  mkdir -p "$DEMO_HOME" "$DEMO_REMOTES" "$DEMO_WORKSPACES_ROOT" "$DEMO_TMP"

  sandbox_env
  write_sandbox_gitconfig
  write_idlegit_workspaces
  copy_gh_auth

  say "starting git daemon on 127.0.0.1:$PORT"
  start_daemon
  ok "daemon up (pid $(cat "$PID_FILE"))"

  build_workspace_commit_demo
  build_workspace_sync_demo
  build_workspace_idlegit

  ok "demo workspaces ready"
  cat <<EOF

  ┌─ next steps ────────────────────────────────────────────────────┐
  │  Manual recording:                                              │
  │    export HOME=$DEMO_HOME
  │    export GIT_CONFIG_GLOBAL=\$HOME/.gitconfig                    │
  │    export IDLEGIT_CONFIG_DIR=\$HOME/.config/idlegit              │
  │    cd $REPO_ROOT && python -m idlegit
  │                                                                 │
  │  Scripted (requires \`brew install vhs\`):                        │
  │    vhs scripts/demo/demo.tape                                   │
  │                                                                 │
  │  Teardown:  $0 down
  └─────────────────────────────────────────────────────────────────┘

EOF
}

cmd_down() {
  stop_daemon
  if [ -d "$DEMO_ROOT" ]; then
    rm -rf "$DEMO_ROOT"
    ok "removed $DEMO_ROOT"
  fi
}

cmd_status() {
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    ok "daemon running (pid $(cat "$PID_FILE"), port $PORT)"
  else
    warn "daemon not running"
  fi
  for ws in "$W1_DIR" "$W2_DIR" "$W3_DIR"; do
    if [ -d "$ws" ]; then
      ok "$(basename "$ws"):"
      ls -1 "$ws" 2>/dev/null | sed 's/^/    /'
    fi
  done
  printf 'sandbox env (paste into the shell that runs idlegit):\n'
  printf '  export HOME=%s\n' "$DEMO_HOME"
  printf '  export GIT_CONFIG_GLOBAL=%s\n' "$DEMO_HOME/.gitconfig"
  printf '  export IDLEGIT_CONFIG_DIR=%s\n' "$DEMO_HOME/.config/idlegit"
}

# ---- entry -----------------------------------------------------------------
case "${1:-up}" in
  up)     cmd_up ;;
  down)   cmd_down ;;
  status) cmd_status ;;
  -h|--help|help)
    cat <<EOF
usage: $0 [up|down|status]

  up      create three demo workspaces + start git daemon (default)
            commit-demo  — suggest/commit/push + propagation demo
            sync-demo    — nested submodules for smart-sync demo
            idlegit      — real clone for GitHub Actions demo
  down    kill daemon, remove all demo state
  status  show daemon + workspace state

env vars:
  DEMO_ROOT        default /tmp/idlegit-demo
  PORT             default 9418 (git daemon)
  IDLEGIT_REMOTE   default https://github.com/jtelwar/Idlegit.git
EOF
    ;;
  *) die "unknown subcommand: $1 (try \`$0 --help\`)" ;;
esac
